### ISSUE TITLE
개발환경 세팅

### ISSUE THREAD

**Issue by seungwonbased** [ssg-salesync/backend#2]
## Description
- item 서비스 개발환경 세팅

## Todo
- [x] config 파일 수정
- [x] init 파일 수정
- [x] api 파일 생성
